#!/bin/sh

DS=192.168.168.251 # DataBase Server Address
Hn="$(cat /proc/sys/kernel/hostname)"
mac="$(cat /sys/class/net/eth0/address | tr ":" "-"   )"
if /bin/ping -q -c 2 -W 1 $DS >/dev/null; then
  echo "IPv4 is up"
echo "$mac  $Hn"
/usr/bin/rsync -e 'ssh -p 22 -i /root/.ssh/id_rsa' -bvupr -zz /mnt/DATA/ root@$DS:/mnt/DATA/SAMBA/GPS

else
echo "network Down"
fi

